"""Update foreign keys

Revision ID: 5ec4e5882243
Revises: 285db968046b
Create Date: 2024-11-13 15:10:35.794263

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5ec4e5882243"
down_revision: Union[str, None] = "285db968046b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
