"""Update foreign keys

Revision ID: cac09d5bdd20
Revises: 5ec4e5882243
Create Date: 2024-11-13 15:16:56.575735

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "cac09d5bdd20"
down_revision: Union[str, None] = "5ec4e5882243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
